### PR TITLE
debezium/dbz#1334 Support quoted type names in enum default values

### LINKED ISSUE #1334: [Postgres] Debezium default values with escaped enum types do not show up [DBZ-8699]
Migrated from [DBZ-8699](https://issues.redhat.com/browse/DBZ-8699)

In order to make your issue reports as actionable as possible, please provide the following information, depending on the issue type.
h1. Bug report

For bug reports, provide this information, please:
h2. What Debezium connector do you use and what version?

Debezium Server 2.5 w/ Postgres
h2. What is the connector configuration?

Example (using Debezium Server 2.5) with Postgres

 

 
h2. What is the captured database version and mode of deployment?

I'm using Debezium examples of the Postgres image.
h2. What behavior do you expect?

 
CREATE TYPE "Status" AS ENUM ('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED');
CREATE TABLE rtang_test2 (
id int primary key,
status "Status" NOT NULL DEFAULT 'DRAFT'
);

INSERT INTO rtang_test2 (id) VALUES (1);
 
I expect to see the default value being passed into the Kafka message. However, the value is not present.
h2. What behavior do you see?

Nothing, see: https://gist.github.com/Tang8330/67f61048eb7f7520aa58d18296b13b42#file-debezium-json-L36-L45

### PR DESCRIPTION
**Pull request by jpechane**
Fixes https://github.com/debezium/dbz/issues/1334

### CODE REVIEW

File: debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/TypeId.java [hunk 1]
```diff
@@ -0,0 +1,199 @@
...
+    /**
+     * Parse the supplied string into a TypeId, handling PostgreSQL quoting rules.
+     * PostgreSQL identifiers can be quoted with double quotes, and quotes within identifiers
+     * are escaped by doubling them.
+     *
+     * @param str the string representation of the type identifier; may not be null
+     * @return the type ID, or null if it could not be parsed
+     */
+    public static TypeId parse(String str) {
+        if (str == null || str.isEmpty()) {
```
Comment (Naros) [inline debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/TypeId.java]: Should this use `Strings.isNullOrEmpty` ?

File: debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/TypeId.java [hunk 2]
```diff
@@ -0,0 +1,199 @@
...
+    }
+
+    /**
+     * Returns a dot-separated String representation of this identifier, quoting all
+     * name parts with the {@code "} char.
+     */
+    public String toDoubleQuotedString() {
+        final var quoted = new StringBuilder();
+
+        if (schemaName != null && !schemaName.isEmpty()) {
```
Comment (Naros) [inline debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/TypeId.java]: Another candidate, `!Strings.isNullOrEmpty`

File: debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/TypeId.java [hunk 3]
```diff
@@ -0,0 +1,199 @@
...
+                Objects.equals(this.typeName, other.typeName);
+    }
+
+    @Override
+    public String toString() {
+        return identifier();
+    }
+
+    private static String typeId(String schema, String type) {
+        if (schema == null || schema.isEmpty()) {
```
Comment (Naros) [inline debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/TypeId.java]: `Strings.isNullOrEmpty`

File: debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/TypeId.java [hunk 4]
```diff
@@ -0,0 +1,199 @@
...
+            return type;
+        }
+        return schema + "." + type;
+    }
+
+    /**
+     * Quotes the given identifier part with double quotes.
+     */
+    private static String quote(String identifierPart) {
+        if (identifierPart == null || identifierPart.isEmpty()) {
```
Comment (Naros) [inline debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/TypeId.java]: `Strings.isNullOrEmpty`

**Review by Naros — COMMENTED** [review]
A few minor items inline.

**Comment by jpechane** [comment]
@Naros Applied, with suggestion
