### PR TITLE
debezium/dbz#1800 Avoid TypeRegistry initialization for BeanRegistry

### LINKED ISSUE #1800: TypeRegistry initialization triggers pg_type query twice at startup
## Bug report

While investigating issues such as #1683, I noticed something that seems unnecessary.

At Debezium startup, it appears that the process which loads all entries from pg_type is executed twice. I think this could be done only once.

**What Debezium connector do you use and what version?**

3.5.0

**What is the connector configuration?**

This behavior does not seem to depend on the configuration, but for example, it occurs with the following:

```
{
  "name": "twice-type-register-connector",
  "config": {
    "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
    "database.hostname": "localhost",
    "database.port": "5432",
    "database.user": "atorik",
    "database.password": "xxx",
    "database.dbname": "db1",
    "topic.prefix": "example",
    "slot.name": "twice_type_register",
    "plugin.name": "pgoutput",
    "publication.autocreate.mode": "disabled",
    "publication.name": "p1"
  }
}
```
---

**What is the captured database version and mode of deployment?**

_E.g. on-premises, with a specific cloud provider, etc._

On-premises.

---

**What behavior do you expect?**

The SQL query that loads all entries from pg_type should be executed only once.

---

**What behavior do you see?**

The SQL query that loads all entries from pg_type is executed twice.

When PostgreSQL is configured with log_statement = all, the logs clearly show that the query defined as [SQL_TYPES](https://github.com/debezium/debezium/blob/0c40827d4fbf62f716dda1849bcf920ddd3a8f3a/debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/TypeRegistry.java#L385) in TypeRegistry is executed twice.

For example:

```
rg "n.nspname != \'pg_toast\'$" data/log/postgresql-2026-04-08.log
23:2026-04-08 22:46:45.712 JST [50915] LOG:  00000: execute <unnamed>: SELECT t.oid AS oid, t.typname AS name, t.typelem AS element, t.typbasetype AS parentoid, t.typtypmod as modifiers, t.typcategory as category, e.values as enum_values FROM pg_catalog.pg_type t JOIN pg_catalog.pg_namespace n ON (t.typnamespace = n.oid) LEFT JOIN (SELECT t.enumtypid as id, array_agg(t.enumlabel) as values FROM pg_catalog.pg_enum t GROUP BY id) e ON (t.oid = e.id) WHERE n.nspname != 'pg_toast'
42:2026-04-08 22:46:45.750 JST [50917] LOG:  00000: execute <unnamed>: SELECT t.oid AS oid, t.typname AS name, t.typelem AS element, t.typbasetype AS parentoid, t.typtypmod as modifiers, t.typcategory as category, e.values as enum_values FROM pg_catalog.pg_type t JOIN pg_catalog.pg_namespace n ON (t.typnamespace = n.oid) LEFT JOIN (SELECT t.enumtypid as id, array_agg(t.enumlabel) as values FROM pg_catalog.pg_enum t GROUP BY id) e ON (t.oid = e.id) WHERE n.nspname != 'pg_toast'
```

---

**Do you see the same behaviour using the latest released Debezium version?**

Yes.

---

**Do you have the connector logs, ideally from start till finish?**

_You might be asked later to provide [DEBUG/TRACE](https://debezium.io/documentation/reference/stable/operations/logging.html) level log._

Yes. I can provide them if needed.

---

**How to reproduce the issue using our [tutorial](https://github.com/debezium/debezium-examples/tree/main/tutorial) deployment?**

Simply starting the PostgreSQL source connector reproduces the issue.

---

**Cause**

In addition to the connection created by connectionFactory, another connection is created for Bean registration. The constructor of TypeRegistry is invoked for both connections:

```java
102:    public ChangeEventSourceCoordinator<PostgresPartition, PostgresOffsetContext> start(Configuration config) {
...
121:        MainConnectionProvidingConnectionFactory<PostgresConnection> connectionFactory = new DefaultMainConnectionProvidingConnectionFactory<>(
                () -> new PostgresConnection(connectorConfig.getJdbcConfig(), valueConverterBuilder, PostgresConnection.CONNECTION_GENERAL));
...
150:        // Manual Bean Registration
151:        beanRegistryJdbcConnection = connectionFactory.newConnection();
```

I placed a breakpoint in the TypeRegistry constructor and captured the backtraces for both invocations.

First invocation:

```
TypeRegistry.<init>(PostgresConnection) (/Users/atorik/debezium/debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/TypeRegistry.java:134)
PostgresConnection.<init>(JdbcConfiguration,PostgresConnection$PostgresValueConverterBuilder,String) (/Users/atorik/debezium/debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java:119)
PostgresConnectorTask.lambda$start$1(PostgresConnectorConfig,PostgresConnection$PostgresValueConverterBuilder) (/Users/atorik/debezium/debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java:122)
0x00007fe0014d5aa8.newConnection() (Unknown Source:0)
DefaultMainConnectionProvidingConnectionFactory.<init>(ConnectionFactory) (/Users/atorik/debezium/debezium-connector-common/src/main/java/io/debezium/jdbc/DefaultMainConnectionProvidingConnectionFactory.java:16)
PostgresConnectorTask.start(Configuration) (/Users/atorik/debezium/debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java:121)
BaseSourceTask.start(Map) (/Users/atorik/debezium/debezium-connector-common/src/main/java/io/debezium/connector/common/BaseSourceTask.java:281)
AbstractWorkerSourceTask.initializeAndStart() (/connect-runtime-4.1.1.jar/org.apache.kafka.connect.runtime/AbstractWorkerSourceTask.class:288)
WorkerTask.doStart() (/connect-runtime-4.1.1.jar/org.apache.kafka.connect.runtime/WorkerTask.class:191)
WorkerTask.doRun() (/connect-runtime-4.1.1.jar/org.apache.kafka.connect.runtime/WorkerTask.class:242)
WorkerTask.run() (/connect-runtime-4.1.1.jar/org.apache.kafka.connect.runtime/WorkerTask.class:298)
AbstractWorkerSourceTask.run() (/connect-runtime-4.1.1.jar/org.apache.kafka.connect.runtime/AbstractWorkerSourceTask.class:83)
Plugins.lambda$withClassLoader$1(ClassLoader,Runnable) (/connect-runtime-4.1.1.jar/org.apache.kafka.connect.runtime.isolation/Plugins.class:254)
0x00007fe0014a8238.run() (Unknown Source:0)
Executors$RunnableAdapter.call() (/java.base/java.util.concurrent/Executors.class:545)
FutureTask.run() (/java.base/java.util.concurrent/FutureTask.class:328)
ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) (/java.base/java.util.concurrent/ThreadPoolExecutor.class:1095)
ThreadPoolExecutor$Worker.run() (/java.base/java.util.concurrent/ThreadPoolExecutor.class:619)
Thread.runWith(Object,Runnable) (/java.base/java.lang/Thread.class:1460)
Thread.run() (/java.base/java.lang/Thread.class:1447)
```

2nd invocation:

```
TypeRegistry.<init>(PostgresConnection) (/Users/atorik/debezium/debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/TypeRegistry.java:134)
PostgresConnection.<init>(JdbcConfiguration,PostgresConnection$PostgresValueConverterBuilder,String) (/Users/atorik/debezium/debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java:119)
PostgresConnectorTask.lambda$start$1(PostgresConnectorConfig,PostgresConnection$PostgresValueConverterBuilder) (/Users/atorik/debezium/debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java:122)
0x00007fe0014d5aa8.newConnection() (Unknown Source:0)
DefaultMainConnectionProvidingConnectionFactory.newConnection() (/Users/atorik/debezium/debezium-connector-common/src/main/java/io/debezium/jdbc/DefaultMainConnectionProvidingConnectionFactory.java:26)
PostgresConnectorTask.start(Configuration) (/Users/atorik/debezium/debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java:151)
BaseSourceTask.start(Map) (/Users/atorik/debezium/debezium-connector-common/src/main/java/io/debezium/connector/common/BaseSourceTask.java:281)
AbstractWorkerSourceTask.initializeAndStart() (/connect-runtime-4.1.1.jar/org.apache.kafka.connect.runtime/AbstractWorkerSourceTask.class:288)
WorkerTask.doStart() (/connect-runtime-4.1.1.jar/org.apache.kafka.connect.runtime/WorkerTask.class:191)
WorkerTask.doRun() (/connect-runtime-4.1.1.jar/org.apache.kafka.connect.runtime/WorkerTask.class:242)
WorkerTask.run() (/connect-runtime-4.1.1.jar/org.apache.kafka.connect.runtime/WorkerTask.class:298)
AbstractWorkerSourceTask.run() (/connect-runtime-4.1.1.jar/org.apache.kafka.connect.runtime/AbstractWorkerSourceTask.class:83)
Plugins.lambda$withClassLoader$1(ClassLoader,Runnable) (/connect-runtime-4.1.1.jar/org.apache.kafka.connect.runtime.isolation/Plugins.class:254)
0x00007fe0014a8238.run() (Unknown Source:0)
Executors$RunnableAdapter.call() (/java.base/java.util.concurrent/Executors.class:545)
FutureTask.run() (/java.base/java.util.concurrent/FutureTask.class:328)
ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) (/java.base/java.util.concurrent/ThreadPoolExecutor.class:1095)
ThreadPoolExecutor$Worker.run() (/java.base/java.util.concurrent/ThreadPoolExecutor.class:619)
Thread.runWith(Object,Runnable) (/java.base/java.lang/Thread.class:1460)
Thread.run() (/java.base/java.lang/Thread.class:1447)
```

The difference in backtraces shows that they originate from different locations in PostgresConnectorTask (lines 121 and 151):

```
< DefaultMainConnectionProvidingConnectionFactory.<init>(ConnectionFactory) (/Users/atorik/debezium/debezium-core/src/main/java/io/debezium/jdbc/DefaultMainConnectionProvidingConnectionFactory.java:16)
< PostgresConnectorTask.start(Configuration) (/Users/atorik/debezium/debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java:121)
---
> DefaultMainConnectionProvidingConnectionFactory.newConnection() (/Users/atorik/debezium/debezium-core/src/main/java/io/debezium/jdbc/DefaultMainConnectionProvidingConnectionFactory.java:26)
> PostgresConnectorTask.start(Configuration) (/Users/atorik/debezium/debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java:151)
```
---

**Consideration/Proposal**

In my environment, after the fix for #1683, the initialization time of TypeRegistry has been significantly reduced, so the performance impact of this issue is currently small. However, if this twice registration is unnecessary, it would be better to avoid it:

- It removes redundant processing
- It would reduce the potential performance impact by roughly half if TypeRegistry initialization becomes expensive because of another reasons.

From what I observed, the connection registered for the Bean registry seems to be used only for ReselectColumns, and TypeRegistry does not appear to be required for that purpose.

Unless there are objections to fix this issue, I am planning to open a PR.

### PR DESCRIPTION
**Pull request by atorik**
Fixes debezium/dbz#1800

## Description
Currently, TypeRegistry was initialized for the `BeanRegistry` connection, but as far as I see, BeanRegistry is only used by Reselect columns and does not require type metadata.
This change skips unnecessary `TypeRegistry` construction for that connection.

**Alternative considered: making TypeRegistry a singleton**
I also considered making `TypeRegistry` a singleton to prevent multiple initializations.

However, `TypeRegistry` currently takes a `PostgresConnection` in its constructor, and in the current design it is created from different connections. Making it a singleton as-is would effectively ignore the connection passed after the first initialization, which feels semantically incorrect.

A cleaner design might require changing the constructor to accept a config object and let `TypeRegistry` manage its own connection internally.
However, that broadens the scope of this PR, so this approach was not pursued here.

## PR Checklist

- [x] I have read the [contribution guidelines](https://github.com/debezium/debezium/blob/main/CONTRIBUTING.md) and the [governance document](https://github.com/debezium/governance/blob/main/GOVERNANCE.md) on PR expectations.
- [x] Minimal changes to code not directly related to your change (e.g. no unnecessary formatting changes or refactoring to existing code)
- [x] One feature/change per PR unless tightly coupled
- [x] Do a rebase on upstream `main`

### CODE REVIEW

**Comment by atorik** [comment]
> Currently, TypeRegistry was initialized for the BeanRegistry connection, but as far as I see, BeanRegistry is only used by Reselect columns and does not require type metadata.

This assumption turned out to be incorrect. 
I have revised the approach so that this PR now reuses the TypeRegistry created for the main connection when establishing the BeanRegistry connection.

File: debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java [hunk 1]
```diff
@@ -148,7 +148,9 @@ public ChangeEventSourceCoordinator<PostgresPartition, PostgresOffsetContext> st
         final PostgresOffsetContext previousOffset = previousOffsets.getTheOnlyOffset();
 
         // Manual Bean Registration
-        beanRegistryJdbcConnection = connectionFactory.newConnection();
+        // We intentionally avoid using connectionFactory, as it would trigger unnecessary
+        // TypeRegistry initialization again for this connection.
+        beanRegistryJdbcConnection = new PostgresConnection(connectorConfig, typeRegistry, PostgresConnection.CONNECTION_GENERAL);
```
Comment (Naros) [inline debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java]: It's also worth noting that within `RelationalSnapshotChangeEventSource`, we rehydrate the `TypeRegistry` when `createConnectionPool` is called, thanks to `newConnection`.

I think it might be beneficial to consider eliminating the construction of `TypeRegistry` in the connection ctor and making it a ctor argument. To accomplish this, a static method on PostgresConnection could use a private ctor to create a dummy connection instance to prime `TypeRegistry`. We'd do this in the connector task before creating the `connectionFactory`.

This allows for:

* The `connectionFactory` can pass it directly on all new connections; no repriming happens.
* Fixes both locations for `connectionFactory.newConnection`, the one you changed here can go back to using `newConnection` again, and the one I referenced in the snapshot change event source.

wdyt @atorik ?

**Review by Naros — COMMENTED** [review]
Hi @atorik, I have a suggestion. Could you take a look and let us know what you think about it and whether the small refactor addresses all corner cases?

File: debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java (hunk 1 above)
Comment (atorik) [reply debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java]: @Naros Thank you for the review.  Your suggested approach seems reasonable.

I gave it a quick try and found that it requires a few adjustments around the tests, but it doesn’t seem to be too many. So I’m going to proceed with implementing it this way.

**Review by Naros — APPROVED** [review]

**Comment by Naros** [comment]
Thanks @atorik, applied!
