### PR TITLE
debezium/dbz#1807 Restore additional condition on MongoDB incremental snapshot offset reload

### LINKED ISSUE #1807: MongoDB conditional incremental snapshot state lost on interruption
## Bug report

**What Debezium connector do you use and what version?**

Debezium versions' v3.0.X and v3.2.X
---

**What is the connector configuration?**

```
{
	"producer.override.buffer.memory": "67108864",
	"connector.class": "io.debezium.connector.mongodb.MongoDbConnector",
	"errors.log.include.messages": "false",
	"transforms.OversizedRecords.oversized.field.behavior": "TRUNCATE",
	"transforms.unwrap.array.encoding": "array_string",
	"topic.creation.default.partitions": "-1",
	"mongodb.connection.string": "********",
	"transforms": "unwrap,DBZToOriginalKeyRename",
	"transforms.OversizedRecords.max.record.size.bytes": "-1",
	"signal.enabled.channels": "source,kafka",
	"value.converter.replace.null.with.default": "true",
	"transforms.InsertStaticValue1.type": "org.apache.kafka.connect.transforms.InsertField$Value",
	"transforms.unwrap.delete.tombstone.handling.mode.rewrite-with-id": "true",
	"transforms.unwrap.drop.tombstones": "true",
	"transforms.InsertStaticValue1.predicate": "IsTopicToEnrich",
	"capture.scope": "database",
	"topic.creation.default.replication.factor": "-1",
	"signal.data.collection": "backoffice.streamkap_signal_historicalorders",
	"transforms.unwrap.type": "io.debezium.connector.mongodb.transforms.ExtractNewDocumentState",
	"transforms.OversizedRecords.type": "com.streamkap.kafka.connect.transforms.OversizedRecords$Value",
	"errors.log.enable": "true",
	"key.converter.ignore.default.for.nullables": "false",
	"key.converter": "org.apache.kafka.connect.json.JsonConverter",
	"transforms.ValueToKey.type": "com.streamkap.kafka.connect.transforms.ValueToKey",
	"mongodb.poll.interval.ms": "60000",
	"transforms.SourceRegexSupport.source.id": "6d6f",
	"signal.kafka.bootstrap.servers": "********",
	"transforms.DBZToOriginalKeyRename.type": "org.apache.kafka.connect.transforms.ReplaceField$Key",
	"predicates.IsTopicToEnrich.pattern": "$^",
	"signal.kafka.topic": "source_6d6f.streamkap_signal",
	"transforms.OversizedRecords.truncation.suffix": "",
	"topic.creation.default.segment.ms": "3600000",
	"transforms.unwrap.field.name.adjustment.mode": "avro",
	"heartbeat.interval.ms": "60000",
	"transforms.unwrap.document.encoding": "document",
	"transforms.unwrap.replace.null.with.default": "true",
	"topic.creation.groups": "excludeheartbeats",
	"predicates": "IsTopicToEnrich",
	"transforms.unwrap.add.fields.prefix": "_streamkap_",
	"producer.override.max.request.size": "67108864",
	"errors.max.retries": "5",
	"capture.target": "backoffice",
	"name": "source_6d6f",
	"errors.tolerance": "none",
	"transforms.InsertStaticValue2.type": "org.apache.kafka.connect.transforms.InsertField$Value",
	"max.batch.size": "2048",
	"snapshot.mode": "no_data",
	"topic.creation.excludeheartbeats.remote.storage.enable": "false",
	"transforms.unwrap.delete.handling.mode": "rewrite",
	"max.queue.size": "8192",
	"collection.include.list": "backoffice.historicalorders,backoffice.streamkap_signal_historicalorders",
	"incremental.snapshot.chunk.size": "128",
	"key.converter.replace.null.with.default": "true",
	"producer.override.batch.size": "1048576",
	"transforms.unwrap.schema.name.adjustment.mode": "avro",
	"cursor.oversize.skip.threshold": "16000000",
	"transforms.OversizedRecords.replace.null.with.default": "true",
	"topic.prefix": "source_6d6f",
	"transforms.InsertStaticKey1.type": "org.apache.kafka.connect.transforms.InsertField$Key",
	"transforms.DBZToOriginalKeyRename.renames": "id:_id",
	"value.converter": "org.apache.kafka.connect.json.JsonConverter",
	"topic.creation.default.local.retention.ms": "86400000",
	"value.converter.ignore.default.for.nullables": "false",
	"transforms.ValueToKey.replace.null.with.default": "true",
	"producer.override.compression.type": "lz4",
	"transforms.unwrap.delete.tombstone.handling.mode": "rewrite",
	"topic.creation.default.cleanup.policy": "delete",
	"transforms.SourceRegexSupport.type": "com.streamkap.kafka.connect.transforms.SourceRegexSupport",
	"snapshot.max.threads": "1",
	"transforms.unwrap.add.headers": "op",
	"topic.creation.default.retention.ms": "604800000",
	"transforms.OversizedRecords.semantic.types.exclude": "io.debezium.data.Json,io.debezium.data.Xml",
	"transforms.unwrap.allow.nested.fields": "",
	"transforms.OversizedRecords.max.field.size.bytes": "1048576",
	"transforms.InsertStaticKey2.type": "org.apache.kafka.connect.transforms.InsertField$Key",
	"cursor.oversize.handling.mode": "split",
	"transforms.unwrap.add.fields": "source.ts_ms,ts_ms",
	"topic.creation.excludeheartbeats.include": "__debezium-heartbeat.*,source_.*\\.streamkap_heartbeat",
	"transforms.InsertStaticValue2.predicate": "IsTopicToEnrich",
	"topic.creation.default.remote.storage.enable": "false",
	"predicates.IsTopicToEnrich.type": "org.apache.kafka.connect.transforms.predicates.TopicNameMatches"
}
```

---

**What is the captured database version and mode of deployment?**

_E.g. on-premises, with a specific cloud provider, etc._

MongoDB Atlas, v7.0, M200

---

**What behavior do you expect?**

After interruption, incremental snapshot resumes and every chunk query uses the `additional-conditions`.

---

**What behavior do you see?**

After interruption, incremental snapshot resumes but chunk queries no longer use the `additional-conditions` (they're null).

---

**Do you see the same behaviour using the latest released Debezium version?**

_Ideally, also verify with the latest Alpha/Beta/CR version._

Not tested but believe it has the same issue-see further details below.

---

**Do you have the connector logs, ideally from start till finish?**

_You might be asked later to provide [DEBUG/TRACE](https://debezium.io/documentation/reference/stable/operations/logging.html) level log._

Yes

[Logs-2026-04-14 09_15_19.txt](https://github.com/user-attachments/files/26702692/Logs-2026-04-14.09_15_19.txt)

Also, please see the offset **before** interruption versus the offset **after**:
```
09/04/2026, 20:51:53
{
	"sec": 1775764304,
	"ord": 421,
	"incremental_snapshot_correlation_id": null,
	"resume_token": "CwEAAAJfZGF0YQD7AAAAODI2OUQ4MDM1MDAwMDAwMUE1MkIwNDJDMDEwMDI5NkU1QTEwMDQxMDREMzUyNzA3QzQ0RTFDOEU1MDY3QzNFQzgwNEUzOTQ2M0M2RjcwNjU3MjYxNzQ2OTZGNkU1NDc5NzA2NTAwM0M2OTZFNzM2NTcyNzQwMDQ2NjQ2RjYzNzU2RDY1NkU3NDRCNjU3OTAwNDYzQzVGNjk2NDAwM0M2MjY0MzUzMDM4NjYzODM0MkQzMzM5NjU2NDJEMzQ2NDMxMzIyRDM5NjQzNTYzMkQ2MzY1NjM2MTMwNjU2NTMwMzgzODM0NjIyRDYzNkM2RjczNjUwMDAwMDAwNAAA",
	"incremental_snapshot_maximum_key": "aced0005757200135b4c6a6176612e6c616e672e4f626a6563743b90ce589f1073296c0200007870000000017372002a6f72672e62736f6e2e74797065732e4f626a65637449642453657269616c697a6174696f6e50726f787900000000000000010200015b000562797465737400025b427870757200025b42acf317f8060854e002000078700000000c69d8033c9a78e273b01d40f6",
	"incremental_snapshot_collections": "[{\"incremental_snapshot_collections_id\":\"backoffice.historicalorders\",\"incremental_snapshot_collections_additional_condition\":\"({$and: [{createddatetimemilliseconds: {$gte: 1775001600000, $lte: 1777593599000}},{scheduleddatetimemilliseconds: {$gte: 1775001600000, $lte: 1777593599000}}]})\"}]",
	"incremental_snapshot_primary_key": "aced0005757200135b4c6a6176612e6c616e672e4f626a6563743b90ce589f1073296c0200007870000000017372002a6f72672e62736f6e2e74797065732e4f626a65637449642453657269616c697a6174696f6e50726f787900000000000000010200015b000562797465737400025b427870757200025b42acf317f8060854e002000078700000000c6954304c36f9e26536f522b6"
}
```

And after:
```
09/04/2026, 21:02:01
{
	"sec": 1775764381,
	"ord": 65,
	"incremental_snapshot_correlation_id": null,
	"resume_token": "zQAAAAJfZGF0YQC9AAAAODI2OUQ4MDM5RDAwMDAwMDQxMkIwNDJDMDEwMDI5NkU1QTEwMDQwRkNFMThDRkMyQkU0RTlCQjY1RTMzM0RCMUVDRThBRDQ2M0M2RjcwNjU3MjYxNzQ2OTZGNkU1NDc5NzA2NTAwM0M2NDY1NkM2NTc0NjUwMDQ2NjQ2RjYzNzU2RDY1NkU3NDRCNjU3OTAwNDY2NDVGNjk2NDAwNjQ2OTU0MkQ2RDVEREQ4RTM1M0JBM0E4RjMwMDAwMDQAAA==",
	"incremental_snapshot_maximum_key": "aced0005757200135b4c6a6176612e6c616e672e4f626a6563743b90ce589f1073296c0200007870000000017372002a6f72672e62736f6e2e74797065732e4f626a65637449642453657269616c697a6174696f6e50726f787900000000000000010200015b000562797465737400025b427870757200025b42acf317f8060854e002000078700000000c69d8033c9a78e273b01d40f6",
	"incremental_snapshot_collections": "[{\"incremental_snapshot_collections_id\":\"backoffice.historicalorders\",\"incremental_snapshot_collections_additional_condition\":null}]",
	"incremental_snapshot_primary_key": "aced000570"
}
```
---

**How to reproduce the issue using our [tutorial](https://github.com/debezium/debezium-examples/tree/main/tutorial) deployment?**

Not prepared

---

The [MongoDB Context](https://github.com/debezium/debezium/blob/b0817be92e98ce42b0b82d997373178eff153880/debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/snapshot/MongoDbIncrementalSnapshotContext.java#L210-L222) on restart (or interruption) of the Connector does not seem to restore the additional conditions (`DATA_COLLECTIONS_TO_SNAPSHOT_KEY_ADDITIONAL_CONDITION`).

The offsets and logs confirm this, because the `incremental_snapshot_collections_additional_conditions` show as **null**, and the latest snapshotted records do not meet the additional conditions criteria.

### PR DESCRIPTION
**Pull request by JonathonO**
## Summary

Fixes https://github.com/debezium/dbz/issues/1807

`MongoDbIncrementalSnapshotContext.stringToDataCollections()` previously read only the collection ID from the serialized offset, silently discarding the `additional_condition` value that `dataCollectionsToSnapshotAsString()` had written. After any connector restart during an incremental snapshot with additional conditions, the filter was permanently lost and the snapshot resumed completely unfiltered.

### Changes

- **Deserialization fix**: Updated `stringToDataCollections()` to restore the `additional_condition` field from the serialized offset alongside the collection ID.
- **Parenthesis stripping**: Added `stripWrappingParentheses()` helper to unwrap the parentheses that `DataCollection.getAdditionalCondition()` adds during serialization, preventing accumulation across save/load cycles that would break `Document.parse`.
- **Unit tests**: Added `MongoDbIncrementalSnapshotContextTest` with three tests covering round-trip preservation, parenthesis accumulation prevention, and empty condition handling.

### How to reproduce

1. Start a MongoDB connector with an incremental snapshot using `additional-conditions`
2. Restart the connector while the snapshot is in progress
3. Observe that the `incremental_snapshot_collections_additional_condition` field in the offset becomes `null` after restart
4. Subsequent chunk queries no longer apply the filtering conditions

### CODE REVIEW

File: debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/snapshot/MongoDbIncrementalSnapshotContextTest.java [hunk 1]
```diff
@@ -0,0 +1,116 @@
...
+import org.junit.jupiter.api.Test;
+
+import io.debezium.connector.mongodb.CollectionId;
+import io.debezium.pipeline.signal.actions.snapshotting.AdditionalCondition;
+import io.debezium.pipeline.source.snapshot.incremental.DataCollection;
+
+public class MongoDbIncrementalSnapshotContextTest {
+
+    /**
+     * Regression test for <a href="https://github.com/debezium/dbz/issues/1807">dbz#1807</a>:
```
Comment (vjuranek) [inline debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/snapshot/MongoDbIncrementalSnapshotContextTest.java]: better to use `@FixFor("debezium/dbz#1807")`

File: debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/snapshot/MongoDbIncrementalSnapshotContextTest.java [hunk 2]
```diff
@@ -0,0 +1,116 @@
...
+     * the MongoDB incremental snapshot context must preserve additional conditions across
+     * serialization round-trips (i.e., across connector restarts). Previously
+     * {@code stringToDataCollections} only restored the collection ID, silently dropping the
+     * {@code additional_condition} field, which caused the snapshot to resume with no filter
+     * on every chunk after a restart.
+     */
+    @Test
```
Comment (vjuranek) [inline debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/snapshot/MongoDbIncrementalSnapshotContextTest.java:31]: Should be placed here `@FixFor("debezium/dbz#1807")` and under `@Test` annotation of the other tests.

**Review by vjuranek — COMMENTED** [review]
Overall LGTM, just a small comment about using `@FixFor` annotation.

**Comment by vjuranek** [comment]
And of course thanks a lot for your PR @JonathonO !

File: debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/snapshot/MongoDbIncrementalSnapshotContextTest.java (hunk 2 above)
Comment (JonathonO) [reply debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/snapshot/MongoDbIncrementalSnapshotContextTest.java:31]: @vjuranek understood! Please check again. I've just force-pushed the change.

File: debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/snapshot/MongoDbIncrementalSnapshotContextTest.java (hunk 1 above)
Comment (JonathonO) [reply debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/snapshot/MongoDbIncrementalSnapshotContextTest.java]: @vjuranek understood! Please check again. I've just force-pushed the change.

**Review by vjuranek — APPROVED** [review]
LGTM now, let's wait for CI

**Comment by vjuranek** [comment]
Merged, thanks @JonathonO !

**Comment by JonathonO** [comment]
> Welcome as a new contributor to Debezium, @JonathonO. Reviewers, please add missing author name(s) and alias name(s) to the [COPYRIGHT.txt](https://github.com/debezium/debezium/blob/main/COPYRIGHT.txt) and [Aliases.txt](https://github.com/debezium/debezium/blob/main/jenkins-jobs/scripts/config/Aliases.txt) respectively.

@vjuranek just a tiny thing I noticed: I don't seem to have been added to the respective lists?

**Comment by vjuranek** [comment]
Thanks for pointing this out @JonathonO ! My fault (but would be fixed during the next release), I added you in https://github.com/debezium/debezium/commit/8e4a367635136bca97651083ab71b72f4f3627df . If you want to provide your full name (which I don't see on your GH profile), feel free to send a PR with it. In such case you full name should be in [COPYRIGHT.txt](https://github.com/debezium/debezium/blob/main/COPYRIGHT.txt) and in [Aliases.txt](https://github.com/debezium/debezium/blob/main/jenkins-jobs/scripts/config/Aliases.txt) mapping between you GH account and full name.
