### PR TITLE
debezium/dbz-1378 Added Debezium level reproducer test

### LINKED ISSUE #1378: Debezium Embedded with Mariadb Connector - gtidSet NPE [DBZ-9243]
Migrated from [DBZ-9243](https://issues.redhat.com/browse/DBZ-9243)

h1. Bug report
h2. What Debezium connector do you use and what version?

io.debezium.connector.mariadb.MariaDbConnector:3.2.0.Final

debezium-connector-binlog:3.2.0.Final
h2. What is the connector configuration?

 
{code:java}
io.debezium.config.Configuration.create()
       .with("name", "mariadb-connector")
       .with("connector.class", "io.debezium.connector.mariadb.MariaDbConnector")
       .with("offset.storage",  "org.apache.kafka.connect.storage.FileOffsetBackingStore")
       .with("offset.storage.file.filename", "temp-folder/offset/offset.dat")
       .with("offset.flush.interval.ms", 60000)
       .with("schema.history.internal", "io.debezium.storage.file.history.FileSchemaHistory")
       .with("schema.history.internal.file.filename", "temp-folder/schema-history/schema.dat")
       .with("database.server.id", "85744")
       .with("database.hostname", "localhost")
       .with("database.port", 3306)
       .with("database.user", "root")
       .with("database.password", "root")
       .with("database.include.list", "trial")
       .with("table.include.list", "trial-2")
       .with("topic.prefix", "mariadb-connector")
       .build(){code}
 
h2. What is the captured database version and mode of deployment?

MariaDB@10.5 in my local PC running in a docker container
h2. What behavior do you see?

 
{code:java}
Caused by: java.lang.NullPointerException: Cannot invoke "com.github.shyiko.mysql.binlog.GtidSet.toString()" because "this.gtidSet" is null	at com.github.shyiko.mysql.binlog.BinaryLogClient.requestBinaryLogStreamMaria(BinaryLogClient.java:827) ~[mysql-binlog-connector-java-0.40.2.jar:0.40.2]	at com.github.shyiko.mysql.binlog.BinaryLogClient.requestBinaryLogStream(BinaryLogClient.java:793) ~[mysql-binlog-connector-java-0.40.2.jar:0.40.2]	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:619) ~[mysql-binlog-connector-java-0.40.2.jar:0.40.2]	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:959) ~[mysql-binlog-connector-java-0.40.2.jar:0.40.2]{code}
binlog is ON mariadb side. Here is also gtid variables in db:
{code:java}
gtid_binlog_pos    0-1-1
gtid_binlog_state    0-1-1
gtid_cleanup_batch_size    64
gtid_current_pos    0-1-1
gtid_domain_id    0
gtid_ignore_duplicates    OFF
gtid_pos_auto_engines    
gtid_slave_pos    
gtid_strict_mode    OFF
wsrep_gtid_domain_id    0
wsrep_gtid_mode    OFF{code}
For whatever reason, I'm always getting this error saying that gtidSet is not set. Then I examined code and noticed that gtidSet is only set in here:

!image-2025-07-22-18-54-50-971.png!

Since I have no filteredGtidSet, client gtidSet is being set as empty string. But in BinaryLogClient:
!image-2025-07-22-18-56-06-713.png!

gtidSet is not being set if gtidStr is empty string which is the case I did mentioned. That concludes with gtidSet being null, and this is the part where the code crashes with NPE:
!image-2025-07-22-18-57-22-980.png!

I cannot disable gtid as it is harcoded unlike in mysql. How should I proceed? Are you aware of this, maybe I'm missing something else

### PR DESCRIPTION
**Pull request by KMohnishM**
Fixes debezium/dbz#1378

#### **Description**
This PR adds a new integration test `shouldStartWithEmptyGtidSet` to `BinlogConnectorIT` to verify the fix for the `NullPointerException`  occurring in the MariaDB connector.

The issue was triggered when the connector attempted to start a binlog stream with an empty or null GTID set, causing a crash in the upstream `mysql-binlog-connector-java` library. This test specifically configures the connector with `gtid.source.excludes = .*` and `snapshot.mode = never` to simulate a start-up state where the GTID set is not yet available, ensuring the connector now handles this path gracefully.

## PR Checklist

- [X] I have read the [contribution guidelines](https://github.com/debezium/debezium/blob/main/CONTRIBUTING.md) and the [governance document](https://github.com/debezium/governance/blob/main/GOVERNANCE.md) on PR expectations.
- [X] Minimal changes to code not directly related to your change (e.g. no unnecessary formatting changes or refactoring to existing code)
- [X] One feature/change per PR unless tightly coupled
- [X] Do a rebase on upstream `main`

### CODE REVIEW

File: debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogConnectorIT.java [hunk 1]
```diff
@@ -2936,6 +2936,19 @@ protected String getExpectedQuery(String statement) {
         return statement;
     }
 
+    @Test
+    @FixFor("DBZ-1378")
```
Comment (vjuranek) [inline debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogConnectorIT.java]: It should be `@FixFordebezium/dbz#1378`

**Review by vjuranek — COMMENTED** [review]
`shouldStartWithEmptyGtidSet` doesn't seem to fail, but as we haven't the fix yet, it should. So it maybe doesn't reproduce the issue.

**Review by vjuranek — COMMENTED** [review]
I tried the test locally (without update binlog client) and the test is still passing, so I believe it still doesn't reproduce the issue.

**Comment by KMohnishM** [comment]
Thanks for review @vjuranek . I have updated the PR to make the reproducer test deterministic across mysql-binlog-connector-java versions as suggested by @jpechane 

Changes:

* The test now captures BinaryLogClient INFO logs during connector startup.
* It asserts that the GTID-based streaming path is not used when GTID is empty.


Local validation matrix after this change:
1. version.mysql.binlog=0.40.6  
   - fails in shouldStartWithEmptyGtidSet
   - assertion fails because the log contains Requesting streaming from GTID set:
2. version.mysql.binlog=0.40.7  
   - passes in shouldStartWithEmptyGtidSet
   - no failure, build is successful

Commands used locally:
```bash
./mvnw -pl debezium-connector-mariadb \
  -DskipTests -DskipITs=false \
  -Dit.test="MariaDbConnectorIT#shouldStartWithEmptyGtidSet" \
  -Ddatabase.hostname=127.0.0.1 \
  -Ddatabase.replica.hostname=127.0.0.1 \
  -Ddatabase.port=3306 \
  -Ddatabase.replica.port=3306 \
  -Ddatabase.ssl.mode=disable \
  -Dversion.mysql.binlog=0.40.6 \
  failsafe:integration-test failsafe:verify
```

```bash
./mvnw -pl debezium-connector-mariadb \
  -DskipTests -DskipITs=false \
  -Dit.test="MariaDbConnectorIT#shouldStartWithEmptyGtidSet" \
  -Ddatabase.hostname=127.0.0.1 \
  -Ddatabase.replica.hostname=127.0.0.1 \
  -Ddatabase.port=3306 \
  -Ddatabase.replica.port=3306 \
  -Ddatabase.ssl.mode=disable \
  -Dversion.mysql.binlog=0.40.7 \
  failsafe:integration-test failsafe:verify
```

File: debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogConnectorIT.java [hunk 2]
```diff
@@ -2936,6 +2943,96 @@ protected String getExpectedQuery(String statement) {
         return statement;
     }
 
+    @Test
+    @FixFor("debezium/dbz#1378")
+    public void shouldStartWithEmptyGtidSet() throws Exception {
+        // The bug is MariaDB-specific in mysql-binlog-client requestBinaryLogStreamMaria.
+        // Skip this reproducer for non-MariaDB connector variants.
+        if (!isMariaDb()) {
+            return;
```
Comment (vjuranek) [inline debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogConnectorIT.java]: I'd suggest to move the test into `MariaDbConnectorIT` and remove this condition.

**Review by vjuranek — COMMENTED** [review]
Thanks @KMohnishM , LGTM now, just move the test into `MariaDbConnectorIT`. Can you also please bump mysql-binlog-connector-java version? IT was already done in additional commit added by @jpechane , but it got lost during force-push. Thanks!

**Comment by KMohnishM** [comment]
@vjuranek I have updated PR accordingly . Could you review it once and confirm if any other changes are required

**Review by vjuranek — APPROVED** [review]
LGTM now

**Comment by vjuranek** [comment]
Thanks @KMohnishM , LGTM now. If you consider it finished as well, please more it from draft state to ready for review.

**Comment by KMohnishM** [comment]
Thanks! @vjuranek I have marked the PR as ready for review

**Comment by vjuranek** [comment]
Merged, thanks @KMohnishM !
